"""Added last_login column to User Model

Revision ID: 723cbb257594
Revises: def9ba642a97
Create Date: 2025-04-09 14:44:39.512687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723cbb257594'
down_revision = 'def9ba642a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
