"""Added suspension functionality

Revision ID: a85843e49c23
Revises: 723cbb257594
Create Date: 2025-04-09 16:26:02.634433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85843e49c23'
down_revision = '723cbb257594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suspend_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspend_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_results', schema=None) as batch_op:
        batch_op.drop_column('suspend_reason')
        batch_op.drop_column('suspend_until')
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
