"""Fixed suspension functionality

Revision ID: afc436be4e4a
Revises: a85843e49c23
Create Date: 2025-04-09 16:42:43.059884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afc436be4e4a'
down_revision = 'a85843e49c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_results', schema=None) as batch_op:
        batch_op.drop_column('suspend_until')
        batch_op.drop_column('suspend_reason')
        batch_op.drop_column('is_suspended')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suspend_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspend_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suspend_reason')
        batch_op.drop_column('suspend_until')
        batch_op.drop_column('is_suspended')

    with op.batch_alter_table('resume_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suspend_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suspend_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
