"""Add security_question and security_answer to users

Revision ID: d27dfa5f5788
Revises: 
Create Date: 2024-12-31 16:25:46.484616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27dfa5f5788'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
